# Generated by Django 3.2.9 on 2021-12-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mbapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='out_of_stock',
            field=models.BooleanField(default=False),
        ),
    ]
